[package]
name = "calculator"
version = "0.1.0"
edition = "2021"
authors = ["Yousuf Abu Shanab"]
description = "Rust calculator CLI"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
